---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+$/
    - /^greenkeeper\/.*$/

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
  matrix:
    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - EMBER_TRY_SCENARIO=ember-lts-2.12
    - EMBER_TRY_SCENARIO=ember-lts-2.16
    - EMBER_TRY_SCENARIO=ember-lts-2.18
    - EMBER_TRY_SCENARIO=ember-release
    - EMBER_TRY_SCENARIO=ember-beta
    - EMBER_TRY_SCENARIO=ember-canary
    - EMBER_TRY_SCENARIO=ember-default

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
  include:
    - addons: skip
      env: nodetest
      script: npm run nodetest
    - stage: Deploy
      addons: ignore
      cache: ignore
      env: ignore
      before_install: ignore
      install: ignore
      script: ignore
      deploy:
        provider: npm
        email: kellyselden@gmail.com
        api_key:
          secure: S7FYQ8Oc2+la4dTaD/3SBz8yMC5a6LbMg5WlhYjO9LERkl87AgI4mOR/KSuERGuXsFLdYmBHn6RsK/LOMH450FJzUTxNNSskut+TbFDxYhm8DwGb1mWKgLe1SgHp/D/qpPIcX4bn5nxOywe+E4ZqKWG10jLRw1Vz1pM6n6KlGpER3q+6xaO1fg4weCemJftAG6ZaixFPQitQVTh2U5cBU7qrTxPz1WN18jS1i2sxOtKfPC5e1jSz/oqOJL+Hgd5VJgcRD/KdPLhmIz1W9O0a8P/q4UnMvsmBB1BVrV5X3+hD4E9SwGTMxB2x1d0WA1XgnEJ9Zitjrk1ugL6VQUiZ8Vhmt5sSE+ehpMfrxeK+ix/2L6I+rb+87YS3Hz3zUfThhqwkcihgNalRc+wuji4LK+VKLNPfCBnaAdjM0irW8rofXY40JVvErrIbVdrZzbFJSSzB6o689jyabFVtzu86sVWoQRzwt7xT54lrYVr9dhnAM2w+EKrXHqXj/Hdduqjn4v7VLbBu3gYP0j0NwPBeONe9kae1aSjZIM3pGiyQ2sq644+Cbcj5DorJRZ41JSsh6fLo6hPhsE6G2yAhmKKU+3iXoCx2HUIL7TsDldQfZKw3jfkoEHGwRexLV+3v/rqqJ6dKED+nTR8WVDVY3xrzKnw0sOWi2aiqM/NujDZFBQE=
        on:
          tags: true
          repo: kellyselden/ember-macro-helpers

before_install:
  - npm config set spin false
  - npm install -g npm@6
  - npm --version

script:
  - npm run lint:js
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
